export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_MESSAGE = 'SAVE_MESSAGE';
export const SET_CONNECTED = 'SET_CONNECTED';
export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';
export const SET_WEBSCOKET_CLIENT = 'SET_WEBSCOKET_CLIENT';
// export const SET_RECENT_STATION = 'SET_RECENT_STATION';
